# Generated by Django 6.0.5 on 2026-05-31 00:16

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('face_index', models.IntegerField(default=0)),
                ('laugh_count', models.IntegerField(default=0)),
                ('bomb_charges', models.IntegerField(default=0)),
                ('consecutive_survived', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=game.models.gen_room_code, max_length=6, unique=True)),
                ('mode', models.CharField(choices=[('hotseat', 'Hotseat Rotation'), ('first_laugh', 'First to Laugh Loses')], default='hotseat', max_length=20)),
                ('content_mode', models.CharField(choices=[('custom', 'Custom Only'), ('merged', 'Merged'), ('api', 'API Only')], default='merged', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('prompt_text', models.TextField(blank=True)),
                ('prompt_type', models.CharField(blank=True, max_length=5)),
                ('laugh_detected_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('hot_seat_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hot_seat_rounds', to='game.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.room')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room'),
        ),
        migrations.CreateModel(
            name='LaughClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_file', models.FileField(upload_to='laugh_clips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gameround')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='game.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='LaughBomb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bomb_type', models.CharField(choices=[('gif', 'GIF'), ('sound', 'Sound')], max_length=10)),
                ('asset_id', models.CharField(max_length=100)),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('fired_at_round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gameround')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bombs_fired', to='game.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bombs', to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('truth', 'Truth'), ('dare', 'Dare')], max_length=5)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prompts', to='game.room')),
            ],
        ),
    ]
