# Generated by Django 6.0.5 on 2026-05-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='mode',
            field=models.CharField(choices=[('solo', 'Solo'), ('hotseat', 'Two Players — Hotseat Rotation'), ('first_laugh', 'Two Players — First to Laugh Loses')], default='hotseat', max_length=20),
        ),
    ]
